// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.Intranet.Infrastructure.Contexts;

#nullable disable

namespace Secco.Intranet.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    [Migration("20260924191032_PerfisColaboradores")]
    partial class PerfisColaboradores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.Intranet.Domain.Diretorio.PerfilColaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_perfil_colaborador");

                    b.Property<string>("Cargo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ds_cargo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<Guid?>("GestorUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gestor_usuario_id");

                    b.Property<string>("NomeExibicao")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("ds_nome_exibicao");

                    b.Property<string>("Ramal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ds_ramal");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_setor");

                    b.Property<string>("Sobre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ds_sobre");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_perfis_colaboradores");

                    b.HasIndex("GestorUsuarioId")
                        .HasDatabaseName("idx_perfis_colaboradores_gestor_usuario_id");

                    b.HasIndex("SetorId")
                        .HasDatabaseName("idx_perfis_colaboradores_id_fk_setor");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uk_perfis_colaboradores_usuario_id");

                    b.ToTable("tb_perfis_colaboradores");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_documento");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_caminho_relativo");

                    b.Property<string>("ChaveEmbrulhada")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_chave_embrulhada");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ds_content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_descricao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("ds_nome_arquivo");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_setor");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint")
                        .HasColumnName("nr_tamanho");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_titulo");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("int")
                        .HasColumnName("ie_visibilidade");

                    b.HasKey("Id")
                        .HasName("pk_documentos");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_documentos_fl_ativo");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_documentos_dt_created_at");

                    b.HasIndex("SetorId")
                        .HasDatabaseName("idx_documentos_id_fk_setor");

                    b.ToTable("tb_documentos");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Inventario.ItemInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_item_inventario");

                    b.Property<string>("AtribuidoANome")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_atribuido_a_nome");

                    b.Property<Guid?>("AtribuidoAUsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("atribuido_a_usuario_id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ds_categoria");

                    b.Property<string>("CodigoPatrimonio")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ds_codigo_patrimonio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_nome");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_setor");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("ie_status");

                    b.HasKey("Id")
                        .HasName("pk_itens_inventario");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_itens_inventario_ds_nome");

                    b.HasIndex("SetorId")
                        .HasDatabaseName("idx_itens_inventario_id_fk_setor");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_itens_inventario_ie_status");

                    b.ToTable("tb_itens_inventario");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Publicacoes.Publicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_publicacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_ativo");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_atualizado_em");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ds_corpo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_criado_por");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_expira_em");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("ie_prioridade");

                    b.Property<DateTimeOffset>("PublicadoEm")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_publicado_em");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_fk_setor");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("ie_tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ds_titulo");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("int")
                        .HasColumnName("ie_visibilidade");

                    b.HasKey("Id")
                        .HasName("pk_publicacoes");

                    b.HasIndex("SetorId")
                        .HasDatabaseName("idx_publicacoes_id_fk_setor");

                    b.HasIndex("Ativo", "PublicadoEm")
                        .HasDatabaseName("idx_publicacoes_fl_ativo_dt_publicado_em");

                    b.ToTable("tb_publicacoes");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Setores.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_setor");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("Fixo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_fixo");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ds_icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_slug");

                    b.HasKey("Id")
                        .HasName("pk_setores");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_setores_fl_ativo");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_setores_ds_nome");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_setores_ds_slug");

                    b.ToTable("tb_setores");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Diretorio.PerfilColaborador", b =>
                {
                    b.HasOne("Secco.Intranet.Domain.Setores.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_perfis_colaboradores_setor");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Documentos.Documento", b =>
                {
                    b.HasOne("Secco.Intranet.Domain.Setores.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_setor");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Inventario.ItemInventario", b =>
                {
                    b.HasOne("Secco.Intranet.Domain.Setores.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_itens_inventario_setor");
                });

            modelBuilder.Entity("Secco.Intranet.Domain.Publicacoes.Publicacao", b =>
                {
                    b.HasOne("Secco.Intranet.Domain.Setores.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_publicacoes_setor");
                });
#pragma warning restore 612, 618
        }
    }
}
