// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Secco.Intranet.Infrastructure.Contexts;

#nullable disable

namespace Secco.Intranet.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    [Migration("20260719143025_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Secco.Intranet.Domain.Setores.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_pk_setor");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("Fixo")
                        .HasColumnType("bit")
                        .HasColumnName("fl_fixo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ds_slug");

                    b.HasKey("Id")
                        .HasName("pk_setores");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_setores_fl_ativo");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_setores_ds_nome");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_setores_ds_slug");

                    b.ToTable("tb_setores");
                });
#pragma warning restore 612, 618
        }
    }
}
