// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Secco.Intranet.Infrastructure.Contexts;

#nullable disable

namespace Secco.Intranet.Migrations.Postgres.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    partial class IntranetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Secco.Intranet.Domain.Setores.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pk_setor");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_created_at");

                    b.Property<bool>("Fixo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_fixo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ds_slug");

                    b.HasKey("Id")
                        .HasName("pk_setores");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_setores_fl_ativo");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_setores_ds_nome");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_setores_ds_slug");

                    b.ToTable("tb_setores");
                });
#pragma warning restore 612, 618
        }
    }
}
